version: '3'

services:
  nginx:
    image: nginx:1.15.5
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./:/app
      - ./.conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
    volumes:
      - ./:/app
      - ./.conf/docker.conf:/usr/local/etc/php-fpm.d/docker.conf
